#!/bin/bash

# Get the directory where this script is located
SCRIPT_DIR=/mnt/Work/ishdeshpa.github.io/ublog

TDAY=$(date +%F)
CURRENT_TIME=$(date +"%I:%M:%S%p")  # Replacing ":" with "-" for safe filenames
NEW_POST="$SCRIPT_DIR/$TDAY-$CURRENT_TIME.md"

# Initialize variables
HEADING=""
CONTENT=""
GIT_PUSH=false
IMAGE=""

# Help text
usage() {
  echo "Usage: $0 [-h heading] [-m markdown] [-g] [-i]"
  echo "  -h heading     : Specify post heading (optional)"
  echo "  -m markdown    : Specify post content (optional)"
  echo "  -i image	 : Specify post image copied from clipboard (optional)"
  echo "  -g             : Push to git after generating post (optional)"
  exit 1
}

# Parse flags
while getopts ":h:m:ig" opt; do
  case $opt in
    h) HEADING="$OPTARG" ;;
    m) CONTENT="$OPTARG" ;;
    i) IMAGE="${NEW_POST%.md}.png"
       wl-paste > "$IMAGE"
    ;;
    g) GIT_PUSH=true ;;
    \?) echo "Invalid option: -$OPTARG" >&2; usage ;;
    :) echo "Option -$OPTARG requires an argument." >&2; usage ;;
  esac
done

# Create post file
if [ -n "$HEADING" ] || [ -n "$CONTENT" ]; then
  {
    if [ -n "$HEADING" ]; then
      echo "# $HEADING"
    fi
    echo
    if [ -n "$CONTENT" ]; then
      echo "$CONTENT"
    fi
    if [ -n "$IMAGE" ]; then
      echo "![image]($(basename $IMAGE))"
    fi
  } > "$NEW_POST"
else
  nvim "$NEW_POST"
fi

# Run post generation
if [ -e "$NEW_POST" ]; then
  "$SCRIPT_DIR/ublog-generate.sh"

  if [ "$GIT_PUSH" = true ]; then
    git -C "$SCRIPT_DIR" add $NEW_POST "ublog-list.json"
    if [ -n "$IMAGE" ]; then 
      git -C "$SCRIPT_DIR" add "${NEW_POST%.md}.png"
    fi;
    git -C "$SCRIPT_DIR" commit -m "Post: $TDAY $CURRENT_TIME"
    git -C "$SCRIPT_DIR" push
  fi
fi
